Update Data Uses
IABTechLab/fideslang pull request #107
Opened 2023-05-17 12:31 UTC by ThomasLaPiana

Closes #104 

### Code Changes

* [ ] _list your code changes here_

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Documentation Updated
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

2023-05-18 14:12 UTC, ThomasLaPiana commented
@NevilleS @mfbrown ready to get y'all's eyes on this 🙂 I did my best to translate the document into exactly the code changes required above, so please double-check that I didn't misunderstand the requirements!

2023-05-19 12:50 UTC, NevilleS requested changes
I *think* the structure looks right here (one nit on an uppercased fides key), but we just need to get the right names & descriptions.

Can you regenerate the CSV version of the data uses, and we'll get some data entry in there to polish this up

2023-05-19 12:50 UTC, NevilleS commented on src/fideslang/default_taxonomy/data_uses.py
>          description="Provide, give, or make available the product, service, application or system.",
Need friendly name & description for "Essential"

2023-05-19 12:50 UTC, NevilleS commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="TODO",
Need friendly description for "Legal Obligation"

2023-05-19 12:50 UTC, NevilleS commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="The promotion of products or services targeted to users based on the the processing of user provided data in the system.",
Similar story here - let's just get some input on what the friendly names & descriptions should be for all these data uses.

2023-05-19 12:50 UTC, NevilleS commented on src/fideslang/default_taxonomy/data_uses.py
> +        fides_key="Finance",
nit: lowercase the key

2023-05-19 12:50 UTC, NevilleS requested changes
I *think* the structure looks right here (one nit on an uppercased fides key), but we just need to get the right names & descriptions.

Can you regenerate the CSV version of the data uses, and we'll get some data entry in there to polish this up

2023-05-19 13:58 UTC, ThomasLaPiana commented
@NevilleS I'm actually not sure how to generate the CSV versions...I'll poke around though, is this a feature/script we have somewhere?

2023-05-22 04:07 UTC, ThomasLaPiana commented on scripts/export_default_taxonomy.py
> +            # For convenience, generate a single "root" node
@NevilleS I'm not sure what these were for/where they came from, but they broke things so I silenced them 😬

2023-05-22 20:02 UTC, NevilleS commented on scripts/export_default_taxonomy.py
> +            # For convenience, generate a single "root" node
Huh, I see - yeah, it looks like that's used for the docs site: https://github.com/ethyca/fideslang/blob/main/mkdocs/docs/js/vis2.js#L730

I'm in favour of getting this merged without fixing those, but we should open a follow-up issue because I think the net result will be that the taxonomy explorer doesn't work, which is a problem because it's super useful 👯

2023-05-23 00:01 UTC, NevilleS requested changes
OK, reviewed & updated the CSV version here: 
[data_uses.csv](https://github.com/ethyca/fideslang/files/11538322/data_uses.csv)


This includes a bunch more edits to the default taxonomy for data uses, as well as all the missing names/descriptions/etc 👍

Also took a closer look at the changes in the PR and added some nits for you ;)

2023-05-23 00:01 UTC, NevilleS commented on data_files/data_subjects.csv
> +automated_decisions_or_profiling,fides_key,is_default,name,organization_fides_key,rights,tags,parent_key,description
@ThomasLaPiana something looks wrong with this CSV, the header row is definitely mangled

2023-05-23 00:01 UTC, NevilleS commented on data_files/data_uses.csv
> +
Where are these blank lines coming from?

2023-05-23 00:01 UTC, NevilleS commented on .github/workflows/pr_checks.yml
> +        run: python scripts/export_default_taxonomy.py
Is the point of this just to ensure the script doesn't error? It doesn't do any checks

2023-05-23 02:28 UTC, NevilleS commented
OK I pushed some local fixes to get the taxonomy visualization updated 👍

2023-05-23 02:32 UTC, NevilleS commented on data_files/data_subjects.csv
> +automated_decisions_or_profiling,fides_key,is_default,name,organization_fides_key,rights,tags,parent_key,description
Nevermind I'm just crazy- that `automated_decisions...` field is one of the valid fields

2023-05-23 02:32 UTC, NevilleS commented on data_files/data_uses.csv
> +
I think it's windows newlines 👎

2023-05-23 02:33 UTC, NevilleS commented on scripts/export_default_taxonomy.py
> +            # For convenience, generate a single "root" node
I restored this logic as it was needed to get the visualization working 👍

2023-05-23 03:23 UTC, ThomasLaPiana commented on .github/workflows/pr_checks.yml
> +        run: python scripts/export_default_taxonomy.py
correct. the scripts were broken without any way of knowing (until I ran them). These are also critical to this repo so it's worth having this check in my opinion

2023-05-23 11:58 UTC, ThomasLaPiana commented
@NevilleS I'm digging in on these, tedious though with lots of changes (names and descriptions changed for existing uses too) but I'm cranking through it

2023-05-23 12:18 UTC, NevilleS commented
> @NevilleS I'm digging in on these, tedious though with lots of changes (names and descriptions changed for existing uses too) but I'm cranking through it

Thanks! Yes, it's tedious but having it pass through several sets of hands will help catch those inconsistencies so keep an eye out

2023-05-23 12:19 UTC, NevilleS commented on .github/workflows/pr_checks.yml
> +        run: python scripts/export_default_taxonomy.py
Makes sense

2023-05-23 12:24 UTC, NevilleS commented
Oh- one thing I just realized. When I exported our worksheet to CSV the ~strikethrough~ styling is lost so you won't see that two of the data uses are meant to be deleted entirely:
* `third_party_sharing.payment_processing`
* `third_party_sharing.fraud_detection`

2023-05-26 13:37 UTC, mfbrown commented
@ThomasLaPiana One requested change... We've updated the descriptions one more time for these. You can find them here: https://docs.google.com/spreadsheets/d/1FNg8vHBmEmWx8SGNxFOutSGxqGULwftzytrsXdBDM2k/edit?usp=sharing

Can you update the descriptions to match, then we're good to go from my side.

2023-05-30 18:44 UTC, mfbrown requested changes
@ThomasLaPiana added a few notes on some minor typos or stylistic changes. Can we also add one last use: `essential.service.authentication` with the description: "Authenticate users to the product, service, application or system."

After that, I think we're good.

2023-05-30 18:44 UTC, mfbrown commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Provices analytics for activities such as system and advertising performance reporting, insights and fraud detection.",
Small type - "Provices"  should be "Provides"

2023-05-30 18:44 UTC, mfbrown commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Enables Finance and accounting activities such as audits and tax reporting.",
This was incorrect in the source document as well, but can you lowercase "Finance"?

2023-05-30 18:44 UTC, mfbrown commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Servies advertisements based on first party data collected or derived about the user.",
Change "Servies" to "Serves"

2023-05-30 18:44 UTC, mfbrown commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Targets advertisements based on data collected, or derived about the user from use of the system.",
This was wrong in the source document as well, but can you remove the comma after collected so this reads "Targets advertisements based on data collected or derived about the user from the use of the system."

2023-05-30 18:44 UTC, mfbrown commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Sends e-mail marketing communications.",
Since we use "email" elsewhere in descriptions, can we be consistent and use "email" here instead of "e-mail"?

2023-05-30 18:44 UTC, mfbrown commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Supporets business processes necessary to the organization's operation.",
Typo - "Supporets" should be "Supports"

2023-05-31 03:28 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Provices analytics for activities such as system and advertising performance reporting, insights and fraud detection.",
```suggestion
        description="Provides analytics for activities such as system and advertising performance reporting, insights and fraud detection.",
```

2023-05-31 03:32 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Enables Finance and accounting activities such as audits and tax reporting.",
```suggestion
        description="Enables finance and accounting activities such as audits and tax reporting.",
```

2023-05-31 03:32 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Servies advertisements based on first party data collected or derived about the user.",
```suggestion
        description="Serves advertisements based on first party data collected or derived about the user.",
```

2023-05-31 03:33 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Targets advertisements based on data collected, or derived about the user from use of the system.",
```suggestion
        description="Targets advertisements based on data collected or derived about the user from use of the system.",
```

2023-05-31 03:33 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Sends e-mail marketing communications.",
```suggestion
        description="Sends email marketing communications.",
```

2023-05-31 03:33 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Supporets business processes necessary to the organization's operation.",
```suggestion
        description="Supports business processes necessary to the organization's operation.",
```

2023-05-31 14:49 UTC, ThomasLaPiana commented
> @ThomasLaPiana added a few notes on some minor typos or stylistic changes. Can we also add one last use: `essential.service.authentication` with the description: "Authenticate users to the product, service, application or system."
> 
> After that, I think we're good.

confirmed by @mfbrown via slack this is the final change and is good to ship

2023-05-31 15:21 UTC, merged