make 'meta' attribute on 'System' and 'Dataset' model more permissive
IABTechLab/fideslang pull request #113
Opened 2023-06-02 21:44 UTC by adamsachs

Closes #111 

### Code Changes

* [ ] make `meta` attribute on `System` and `Dataset` models more permissive to allow for nested dictionaries/objects

### Steps to Confirm

* [ ] can do some manual testing in `fides` using the system API, once we integrate this change.

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Documentation Updated
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

see #111 for more context!

2023-06-05 18:38 UTC, adamsachs commented on CHANGELOG.md
changelog needed some general hygiene, figured i'd just do it here

2023-06-05 18:41 UTC, adamsachs commented
@ThomasLaPiana could i get a quick look at this? should be pretty straightforward, i hope 😄 

i'd like to cut a point release with this change after it's merged, if that's alright, as i'm hoping to get it integrated over to `fides` (https://github.com/ethyca/fides/pull/3463) before the next fides release later this week.

2023-06-06 13:59 UTC, ThomasLaPiana commented on src/fideslang/models.py
> +    meta: Optional[Dict[str, Any]] = Field(  # type: ignore[misc]
sorry to nit here, but I feel like this should be a reusable field since we're using it in at least two places and can move it to others later if we want.

See the top of the file for examples of reusable fields, you can add it there and update the description and this should be good to go!

2023-06-06 14:00 UTC, ThomasLaPiana commented on src/fideslang/models.py
> +class Dataset(FidesModel, FidesopsMetaBackwardsCompat):  # type: ignore[misc]
academically i'm curious what the type error is?

2023-06-06 14:01 UTC, ThomasLaPiana requested changes
small abstraction change request

2023-06-06 14:02 UTC, adamsachs commented on src/fideslang/models.py
> +    meta: Optional[Dict[str, Any]] = Field(  # type: ignore[misc]
oh nice, hadn't noticed those - good idea! will go for it

2023-06-06 14:09 UTC, adamsachs commented on src/fideslang/models.py
> +class Dataset(FidesModel, FidesopsMetaBackwardsCompat):  # type: ignore[misc]
complaining about explicit `Any`. it was odd to me that it was complaining both on the line defining the `meta` attribute (L532) and the line defining the wrapping class (L529), but it was...so i just decided to satisfy it 🤷 

i.e. here's what i get from `mypy` when i remove it:
```
src/fideslang/models.py:533: error: Explicit "Any" is not allowed  [misc]
    class Dataset(FidesModel, FidesopsMetaBackwardsCompat):

```

2023-06-06 14:18 UTC, adamsachs commented on src/fideslang/models.py
> +    meta: Optional[Dict[str, Any]] = Field(  # type: ignore[misc]
updated in https://github.com/ethyca/fideslang/pull/113/commits/070d05cb40272fd0222d587929fd48d417f44888

2023-06-06 14:30 UTC, ThomasLaPiana commented on src/fideslang/models.py
> +class Dataset(FidesModel, FidesopsMetaBackwardsCompat):  # type: ignore[misc]
interesting, thanks for the note!

2023-06-06 14:43 UTC, ThomasLaPiana commented on src/fideslang/models.py
> +    meta: Dict = meta_field
I realized that since we actually want to allow arbitrary stuff, there is no point in type enforcing the object internals! this also removes the need for the ignores

2023-06-06 14:44 UTC, ThomasLaPiana commented on src/fideslang/models.py
> +    default_factory=dict,
I don't see a reason to allow `None` here, this way users can do `dataset.meta.get("somekey")` without first having to do an existence check, and it will still evaluate to false in a bool check

2023-06-06 14:44 UTC, ThomasLaPiana approved these changes

2023-06-06 15:04 UTC, merged