Add new categories and uses to the Default Taxonomy
IABTechLab/fideslang pull request #144
Opened 2023-08-07 08:28 UTC by ThomasLaPiana

Closes #142 
Closes #141 

### Description Of Changes

This PR is focused on adding 

### Code Changes

* [ ] _list your code changes here_

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Documentation Updated
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

2023-08-09 07:59 UTC, ThomasLaPiana commented
@NevilleS I'm thinking this needs a 2.0 bump? These are pretty large changes, and will definitely break things as we don't have proper versioning in yet

2023-08-09 08:09 UTC, ThomasLaPiana commented
I'm investigating CI failures here due to our friend `PyYaml` and `Cython`: https://github.com/yaml/pyyaml/issues/736

2023-08-09 17:31 UTC, ThomasLaPiana commented
@pattisdr will merging this hinder your in-flight work in any way?

2023-08-09 17:34 UTC, pattisdr commented
Not sure, you seem to be working in different files though.  Either way we both have items that need to get in this sprint -

2023-08-09 21:38 UTC, pattisdr requested changes
@ThomasLaPiana Large effort here!

Reviewed by comparing taxonomy files [to this confluence doc](https://ethyca.atlassian.net/wiki/spaces/PM/pages/2740027499/Fideslang+updates). I understand there have been other conversations since this doc and it is outdated in places so I'll leave the details for you to sort - 

Nice testing additions as well.  Another nice test to add might be one to make sure all the parents (and their parents, etc) exist.

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
>          name="Essential for Serivce Operations Support",
Existing typo Serivce but it also looks like the new name is supposed to be: Essential for Operations Support

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
>          name="Essential for Serivce Support Optimization",
Existing typo Serivce

updated: looks like this whole data use can be removed?

2023-08-09 21:38 UTC, pattisdr commented on data_files/data_uses.json
> +            "fides_key": "functional.storage",
This removed "improve.system" key is referenced in failing_nested_dataset.yml, system.md, and demo_system.yml

2023-08-09 21:38 UTC, pattisdr commented on data_files/data_uses.yml
> -- fides_key: improve
Former `improve` referenced in data_uses.md.  Actually that whole file will likely need a revamp at some point

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
> +        description="Essential to optimize and improve support for for the product, service, application or system.",
Duplicate words "for for"

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
>          fides_key="essential.service.operations.support.optimization",
Referencing [this doc](https://ethyca.atlassian.net/wiki/spaces/PM/pages/2740027499/Fideslang+updates#Taxonomy-updates-for-data-uses-%5BmediaInline%5D) - if current, it looks like this field should have been replaced by essential.service.operations.improve, but it's still here -

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
>          name="Essential for Service Operations",
It looks like this should be the new name: Essential for Operations

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
>          description="Ensures the operation of the product, service, application or system.",
It looks like this should be the new (similar) description: Essential to ensure the operation of the product, service, application or system.

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
>          name="Essential for Service Payment Processing",
It looks like new name should be: Essential for Payment Processing

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
>          description="Processes payments for the product, service, application or system.",
It looks like new description should be similar: Essential to process payments for the product, service, application or system.

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
> +    category.is_default = True
Ah bravo!

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
> -        organization_fides_key="default_organization",
Are we removing these because organizations have their own fides keys now?

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> +        name="Account Information",
copy/paste Should be Account Settings

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> +        fides_key="user.authorization.credentials",
It looks like the fides_key for this one needs to be `user.authorization.credentials.unencrypted`, and we need to separately add `user.authorization.credentials`.

And if we decided to skip the proposed `user.authorization.credentials.unencrypted`, the description here needs to be updated instead.

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> +        name="Account Credentials.",
Doc has Account password here instead

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> +        description="Retinal encoded data about a subject.",
Is that really how you say that, "Retinal encoded?" Encoded via the retina? Just English question

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> +        parent_key="user.id",
It doesn't seem like there's a fides_key of `user.id` yet

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> +        description="Imprecise location derived form sensors (more than 500M).",
derived *from*

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> +        description="Precise location derived form sensors (less than 500M).",
derived *from*

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
>          fides_key="user.observed",
This is supposed to be removed in favor of user.behavior

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
>          fides_key="user.non_specific_age",
Should be removed in favor of user.demographic.age_range

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
>          fides_key="user.date_of_birth",
Should be removed in favor of user.demographic.date_of_birth

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> +        fides_key="user.profiling",
user.profiling should be removed in favor of user.demographic.profile

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
>          fides_key="user.religious_belief",
Should be removed in favor of user.demographic.religious_belief

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
>          fides_key="user.financial.account_number",
Should be removed in favor of user.financial.bank_account

2023-08-09 21:38 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> +        fides_key="user.genetic",
Should be removed in favor of user.health_and_medical.genetic

2023-08-09 21:38 UTC, pattisdr commented on data_files/data_categories.csv
> -fides_key,is_default,name,organization_fides_key,parent_key,tags,description
What is the purpose of these csv/yml/and json files? Just curious how people use them

2023-08-09 21:38 UTC, pattisdr commented on data_files/data_uses.json
> +            "parent_key": "functional.service",
Looks like we need to add "functional.service" -

2023-08-09 22:05 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> -        fides_key="user.payment.financial_account_number",
Where is it specified that we are removing user.payment.financial_account_number?

2023-08-09 22:05 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> -        fides_key="user.biometric_health",
Where is it specified that we are removing this one? user.biometric_health

2023-08-09 22:05 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_categories.py
> +        fides_key="user.authorization.biometric",
Where is this one coming from?

EDIT: found it in a google sheets conversation -

2023-08-10 14:09 UTC, ThomasLaPiana commented on data_files/data_categories.csv
> -fides_key,is_default,name,organization_fides_key,parent_key,tags,description
They're used for our auto-generated docs as well as making it easier for non-engineers to more easily consume the default taxonomy

2023-08-14 10:29 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_uses.py
> +    category.is_default = True
makes the file a _little_ easier to parse visually without redundant fields! Way more changes coming here in the PR on top of this one...

2023-08-14 10:43 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_categories.py
> +        description="Retinal encoded data about a subject.",
This doesn't sound right to me either...

"Retinal data" or "Encoded retinal data" makes more sense to me

2023-08-14 10:44 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_categories.py
> +        description="Imprecise location derived form sensors (more than 500M).",
this is a really good place to use "code suggestions" :)

2023-08-14 10:46 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_categories.py
> +        description="Precise location derived form sensors (less than 500M).",
code suggestion

2023-08-16 06:02 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_categories.py
> -        fides_key="user.biometric_health",
there is now a `user.biometric.health`

2023-08-16 06:03 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_categories.py
> -        fides_key="user.payment.financial_account_number",
`user.financial.account_number`

2023-08-16 06:06 UTC, ThomasLaPiana commented
@pattisdr the review here is kind of confusing...

I was given a CSV file and told that it is the intended end-state of the taxonomy (one CSV for each type actually, categories and uses)

I converted those CSV files into google sheets and marked them up/had comments as per the linked sheets at the top of the PR

Anything that _isn't_ in that file, I took as an explicit flag to remove it from the current taxonomy. There was additional discussion in the comments around what to do with certain fields

Hugely appreciate the thorough review here! I know it's hard to follow, I want @rsilvery to chime in as well and confirm the CSV in this PR matches the requirements. This is very detail-oriented work and deserves a lot of eyes on to verify my changes!

2023-08-16 06:11 UTC, ThomasLaPiana commented on data_files/data_uses.json
> +            "fides_key": "functional.storage",
if the tests are passing, the name itself isn't really relevant. Tests shouldn't be tied to a specific version of the taxonomy (outside of the specific `default taxonomy` tests we have)

2023-08-16 06:11 UTC, ThomasLaPiana commented on data_files/data_uses.yml
> -- fides_key: improve
Yeah I'll open a follow-up issue for a full audit for Fideslang 2.0

2023-08-16 06:15 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_uses.py
> -        organization_fides_key="default_organization",
no, it's because I didn't need to add it in the first place!
https://github.com/ethyca/fideslang/blob/main/src/fideslang/models.py#L69

2023-08-16 15:53 UTC, pattisdr approved these changes
thanks for your changes here - approved with the addition of the missing parent fides key item

2023-08-16 15:53 UTC, pattisdr commented on CHANGELOG.md
> +
Changelog will need to be updated now that we've released 1.4.4

2023-08-16 15:53 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
> +        parent_key="functional.service",
This parent key still does not exist in this taxonomy.

https://github.com/ethyca/fideslang/pull/144#discussion_r1289216214

I think a new test is useful at this point:
```python
    @pytest.mark.parametrize("data_type", ["data_category", "data_use"])
    def test_parent_key_exists(self, data_type) -> None:
        keys = [x.fides_key for x in getattr(DEFAULT_TAXONOMY, data_type)]
        for key in keys:
            expanded_keys: List[FidesKey] = []
            for i, split in enumerate(key.split(".")):
                expanded_keys.append(expanded_keys[-1] + "." + split if i else split)
                if expanded_keys[-1] not in keys:
                    raise Exception(
                        f"Missing parent key {expanded_keys[-1]} for {data_type}"
                    )
```

2023-08-16 16:32 UTC, ThomasLaPiana commented on src/fideslang/default_taxonomy/data_uses.py
> +        parent_key="functional.service",
This is super helpful! Next time feel free to contribute directly, I have short toes 🙂

2023-08-16 17:33 UTC, merged

2023-08-17 17:54 UTC, rsilvery commented
Is there still something I need to review here? I don't get GH notifications in a timely way so please ping me on Slack if so.