Rachel purpose 11
IABTechLab/fideslang pull request #171
Opened 2023-10-02 16:08 UTC by rsilvery

Partially closes https://github.com/ethyca/fides/issues/4226
❗ Assumes this goes out with 2.1.1. If not, that needs to be updated in this PR.

### Description Of Changes

- Updated data uses to assist with GVL mapping as such:
    - Personalize.profiling ->  personalize.content.profiling
    - Add personalize.content.profiled
    - Add personalize.content.limited
- Updated GVL mappings as such:
    - p5: personalize.profiling -> personalize.content.profiling 
    - p6:  personalize.content -> personalize.content.profiled 
    - p11: personalize.system (placeholder) -> personalize.content.limited
    
Will need help with a migration script. Updating Adam's ingestion script.

2023-10-02 16:16 UTC, pattisdr requested changes

2023-10-02 16:16 UTC, pattisdr commented on data_files/data_uses.csv
>  data_use,,,,,Data Use,,,,,,,,,
@rsilvery there are several other files that need to be changed, this csv I think is generated for convenience, but it is this file that is the main one: src/fideslang/default_taxonomy/data_uses.py.  And then there's some other convenience files that need to be added - 

See the files changed here:

https://github.com/ethyca/fideslang/pull/144/files#diff-e3c8071290cee31ab5aa8acffee2d2a35ad3964e12e67b1664a79e7835f886de

Since you're adding and updating data uses, you'll also need to specify which version the new ones were added, and for the one you're updating, in which version it was deprecated.  Since a data use is changing it seems like there's a corresponding migration needed in fides.

2023-10-02 16:16 UTC, pattisdr commented on src/fideslang/gvl/gvl_data_use_mapping.json
> +            "data_uses": ["personalize.content.profiled"],
what is the difference between "personalize.content.profiling" and "personalize.contend.profiled"?

2023-10-02 16:23 UTC, rsilvery commented on data_files/data_uses.csv
>  data_use,,,,,Data Use,,,,,,,,,
Okay @ThomasLaPiana  had instructed PM in the past to update this CSV. Maybe he has a script he uses for update?

2023-10-02 16:25 UTC, rsilvery commented on src/fideslang/gvl/gvl_data_use_mapping.json
> +            "data_uses": ["personalize.content.profiled"],
One refers to the action of creating a profile for these purposes, the other refers to using that profile, vs limited info about the user. Make sense?

2023-10-02 16:56 UTC, pattisdr commented on src/fideslang/gvl/gvl_data_use_mapping.json
> +            "data_uses": ["personalize.content.profiled"],
OK thanks for clarifying

2023-10-02 17:06 UTC, pattisdr commented on data_files/data_uses.csv
>  data_use,,,,,Data Use,,,,,,,,,
Apologies Rachel, I misunderstood why I was getting tagged in for review! One of us can usher this forward and add the remaining pieces here and in fides.

2023-10-02 23:58 UTC, NevilleS reviewed
Question for me

2023-10-02 23:58 UTC, NevilleS commented on data_files/data_uses.csv
> +personalize.content.profiling,TRUE,,,,Profiling for Personalization,default_organization,personalize.content,,,,,2.0.1,,Creates profiles for the purpose of serving content.
Question: what's the intended difference between:
1. `personalize.content.profiled`
2. `personalize.content.profiling`

2023-10-03 00:13 UTC, NevilleS commented on data_files/data_uses.csv
> +personalize.content.profiling,TRUE,,,,Profiling for Personalization,default_organization,personalize.content,,,,,2.0.1,,Creates profiles for the purpose of serving content.
Ah I see now - "profiled" is the data use for when selecting personalized ads/content/etc based on an existing content profile.

The key name is throwing me for a loop

2023-10-03 00:52 UTC, pattisdr commented on data_files/data_uses.csv
> +personalize.content.profiling,TRUE,,,,Profiling for Personalization,default_organization,personalize.content,,,,,2.0.1,,Creates profiles for the purpose of serving content.
The version_added will need to change, we're already at 2.1.0 -

2023-10-03 00:55 UTC, pattisdr commented
@ThomasLaPiana I was tagged on review here, I added some [unique name cleanup here](https://github.com/ethyca/fideslang/pull/171/commits/5c3336dcdc51f7001cb32bcb8c570c1ad6430070) and then attempted to use your new pattern for [deprecating an old use when adding a new one](https://github.com/ethyca/fideslang/pull/171/commits/3dcdb1ecfa99d01e8f209712efe3a72f20640429).  Is this in line with what you had in mind?

Also, do you have existing scripts for building the files in the various formats?

2023-10-03 01:07 UTC, rsilvery commented on data_files/data_uses.csv
> +personalize.content.profiling,TRUE,,,,Profiling for Personalization,default_organization,personalize.content,,,,,2.0.1,,Creates profiles for the purpose of serving content.
What should it be?

2023-10-03 01:23 UTC, pattisdr commented on data_files/data_uses.csv
> +personalize.content.profiling,TRUE,,,,Profiling for Personalization,default_organization,personalize.content,,,,,2.0.1,,Creates profiles for the purpose of serving content.
My guess is 2.1.1 that's what I added in a corresponding commit here in another file.  I was going to wait and see if Thomas could point me towards the scripts he uses too

2023-10-04 12:25 UTC, NevilleS commented on data_files/data_uses.csv
> +personalize.content.profiling,TRUE,,,,Profiling for Personalization,default_organization,personalize.content,,,,,2.0.1,,Creates profiles for the purpose of serving content.
Disregard - let's ship it. We can tweak the display names / descriptions to assist in understanding these but I don't want to gum up the works!

2023-10-04 12:26 UTC, NevilleS commented on data_files/data_uses.csv
> +personalize.content.profiling,TRUE,,,,Profiling for Personalization,default_organization,personalize.content,,,,,2.0.1,,Creates profiles for the purpose of serving content.
Thomas is OOTO right now, we can get this one shipped!

2023-10-04 23:42 UTC, pattisdr commented on data_files/data_uses.csv
> +personalize.content.profiling,TRUE,,,,Profiling for Personalization,default_organization,personalize.content,,,,,2.0.1,,Creates profiles for the purpose of serving content.
I plan to pick this one up tomorrow, didn't get to it today!

2023-10-05 18:48 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
> +        replaced_by="personalize.content.profiling",
OK I'm getting close @adamsachs  I'm just on the fides side trying to figure out the impacts of our first data use where we're "deprecating it" instead of "deleting it" entirely

2023-10-05 19:09 UTC, adamsachs commented on src/fideslang/default_taxonomy/data_uses.py
> +        replaced_by="personalize.content.profiling",
sounds good, i'll hold off on review though until you've confirmed integration there? if you'd prefer i take a preliminary look now then i can go for it 👍

2023-10-05 20:32 UTC, pattisdr commented on src/fideslang/default_taxonomy/data_uses.py
> +        replaced_by="personalize.content.profiling",
OK I think this is ready Adam!

2023-10-05 20:37 UTC, adamsachs commented on data_files/data_uses.json
just curious if you found a script or utility to help generate these @pattisdr

2023-10-05 20:41 UTC, adamsachs approved these changes
looks good @pattisdr ! just one small thing that i'm not sure is a problem or me just reading the diff wrong...

going to tentatively approve so that you're not blocked on my approval, trust you can resolve/adjust as needed 👍

2023-10-05 20:41 UTC, adamsachs commented on data_files/data_uses.yml
> +- version_added: 2.1.1
am i just reading the diff wrong? or is this a slight error, i.e. wasn't `personalize.system` already existing before this update?

2023-10-05 20:57 UTC, pattisdr commented on data_files/data_uses.yml
> +- version_added: 2.1.1
I just ran Thomas's script to regenerate!  it looks like the diff is just weird.  The personalize.system is below on L738 and it's re-adding up here?  This version_added is for the record below, personalize.system still has 2.0.0 in this file.

2023-10-05 20:58 UTC, pattisdr commented on data_files/data_uses.json
I did! Found it immediately once I actually looked for it https://github.com/ethyca/fideslang/tree/main/scripts

Thanks Thomas!

2023-10-05 20:58 UTC, pattisdr commented on data_files/data_uses.json
He added documentation and everything.

2023-10-05 20:59 UTC, pattisdr approved these changes

2023-10-05 20:59 UTC, merged