Add `DataFlow`s, define `egress` and `ingress` on `System`s and `PrivacyDeclaration`s
IABTechLab/fideslang pull request #85
Opened 2022-09-16 01:32 UTC by PSalant726

Closes #83

### Code Changes

* [x] Define `egress` and `ingress` `FidesKey`s on `PrivacyDeclaration`s
* [x] Define the `DataFlow` resource model, and the companion `FlowableResources` `Enum`
* [x] Define `egress` and `ingress` `DataFlow`s on `System` resources
* [x] Validate that any `PrivacyDeclaration`s applied to a given `System` only reference `egress` and `ingress` `FidesKey`s that are also defined in that System's `egress` and `ingress` `DataFlow`s, respectively
* [x] Fix some broken stuff

### Steps to Confirm

* [ ] Run the tests (they should pass)

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* [ ] Documentation Updated
* [x] Issue Requirements are Met
* [ ] ~Relevant Follow-Up Issues Created~
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

2022-09-16 17:21 UTC, NevilleS requested changes
Couple notes and nits

2022-09-16 17:21 UTC, NevilleS commented on src/fideslang/models.py
> +        description="The resources to which data is sent."
I think this description can be a bit more helpful- for example:
```
The list of resources to which a data is sent. This is a list of `fides_key` entries, each of which must match an entry on the parent `egress` field on the `System` itself
```

or similar

2022-09-16 17:21 UTC, NevilleS commented on src/fideslang/models.py
> +        description="The resources from which data is received."
Same as above

2022-09-16 17:21 UTC, NevilleS commented on src/fideslang/models.py
> +    fides_key: FidesKey = Field(
I don't think we should allow a `fides_key: user` to be a special case here, so I'd argue this should be an optional field.

2022-09-16 17:21 UTC, NevilleS commented on src/fideslang/models.py
> +        description="Identifies the System or Dataset resource with which the communication occurs. May also be 'user', to represent communication with the user(s) of a System.",
I think the docs should say "if `type: user`, the `fides_key` must be null"

2022-09-16 17:21 UTC, NevilleS commented on tests/fideslang/test_models.py
> +    def test_system_no_ingress(self) -> None:
Not seeing any tests for the special case of `type: user` and some of the validations we should enforce there

2022-09-16 17:54 UTC, PSalant726 commented on src/fideslang/models.py
> +    fides_key: FidesKey = Field(
We discussed this special case and decided it was reasonable?

Separately, if we allow `None` here, then any `PrivacyDeclaration`s that want to contextualize themselves as data coming to/from users would need to include `None` in their `ingress` and/or `egress` arrays. This gets messy, as `None` is not a valid `FidesKey` (nor should it be). Even if `None` _were_ a valid `FidesKey`, including `None` elements in arrays results in unnecessary allocations, which would just get garbage collected. So, those same `PrivacyDeclaration`s would define their `None` egress/ingress in the YAML files, but the resulting resource models would be created as empty arrays.

If you don't like `user` as the "special case `FidesKey`" then we can always use something else, but `None` does not work.

2022-09-16 17:54 UTC, PSalant726 commented on tests/fideslang/test_models.py
> +    def test_system_no_ingress(self) -> None:
Was this comment assuming that we would update the "special case `FidesKey`" for users to `None`? If not, what tests/validations would you expect to see?

2022-09-16 19:11 UTC, conceptualshark approved these changes
👍 Thanks for the docs updates!

2022-09-19 02:33 UTC, ThomasLaPiana commented on src/fideslang/models.py
> +    fides_key: FidesKey = Field(
Agreeing with @PSalant726 here, having `user` as a special `fides_key` allows us to treat `user` as a first-class object, otherwise we'll complicate a lot of the logic here

2022-09-19 02:44 UTC, ThomasLaPiana commented on src/fideslang/models.py
> +    @validator("privacy_declarations", each_item=True)
we would also need a check here that any resources with the type of `user` also have `user` as the fides_key, since we're now supporting that as a special case here

2022-09-19 02:47 UTC, ThomasLaPiana commented on tests/fideslang/test_models.py
> +                system_dependencies=[],
`system_dependencies` is currently used for building the data map, but this language change will make that obsolete, we should communicate this change with @mfbrown and plan how to execute that change over there

I think we should also deprecate that field in this release

2022-09-19 02:48 UTC, ThomasLaPiana commented on tests/fideslang/test_models.py
> +                system_dependencies=[],
Adding a validator that gives a `DeprecationWarning` if that field is set by the user seems like a good option

2022-09-19 02:49 UTC, ThomasLaPiana commented on tests/fideslang/test_models.py
> +    def test_system_no_ingress(self) -> None:
`test_user_ingress_has_user_fides_key` or something similar I'd think, and we'd need a validator to go along with it

2022-09-19 02:54 UTC, ThomasLaPiana reviewed
Left some comments, specifically we need to think about how to deal with `system_dependencies` and `dataset_references` either here or in a future issue as those are now redundant
Also I think `ingresses` and `egresses` should be used as the proper plural forms

2022-09-19 02:55 UTC, ThomasLaPiana commented
[Kubernetes agrees its ingresses](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)

2022-09-19 17:31 UTC, NevilleS commented on src/fideslang/models.py
> +    fides_key: FidesKey = Field(
🤔 OK I think I follow. I feel like the special `fides_key` of `"user"` might surprise us later - for example, it's technically a valid `data_category` in the default taxonomy.

2022-09-19 17:34 UTC, NevilleS commented on tests/fideslang/test_models.py
> +    def test_system_no_ingress(self) -> None:
Yeah- whether or not the fides_key is optional, there's definitely special logic for `user` that deserves some test cases

2022-09-19 23:46 UTC, PSalant726 commented on tests/fideslang/test_models.py
> +    def test_system_no_ingress(self) -> None:
The existing `System` validator - `privacy_declarations_reference_data_flows` - would already validate the "user" case. I've added a test to confirm. I also added a validator to `DataFlow`s to guarantee that if either the `fides_key` or `type` is set to "user", then so would be the other.

2022-09-20 00:19 UTC, PSalant726 commented
Created #86 to track the removal of `PrivacyDeclaration.dataset_references` and `System.system_dependencies`. It should be addressed once a release is created with the changes on this PR.

2022-09-20 02:32 UTC, ThomasLaPiana commented on src/fideslang/models.py
> +    fides_key: FidesKey = Field(
Due to the fact that fides_keys are only unique per-resource, everywhere we reference a fides_key we also describe what type of resource it is, so this collision shouldn't happen unless we drastically change fideslang in the future, and at that time we can tackle this I'd think

2022-09-20 02:37 UTC, ThomasLaPiana approved these changes
Good change, good tests 👍

2022-09-20 15:49 UTC, NevilleS approved these changes
LGTM. I'm a little suspicious about deprecating `dataset_references`, only because it's tightly woven into the policy evaluation on fides today, but I agree that it overlaps enough with the ingress/egress declaration that we can find a way to make that work.

2022-09-20 16:04 UTC, merged