Cg docs 2.0
IABTechLab/fideslang pull request #93
Opened 2022-11-01 18:02 UTC by conceptualshark

### Code Changes

* Prepped last of the docs for 2.0 release 
* Removed lingering fidesctl/fidesops references
* Update footer links to 2.0 docs
* Updated CSS to appropriate brand coloring
* 
### Steps to Confirm

* build the docs successfully

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [x] Documentation Updated
* [x] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

2022-11-15 13:32 UTC, ThomasLaPiana commented on mkdocs/docs/syntax.md
> +The Fides language is intentionally simple. To assure this, Fides declarations use predefined primitives (e.g. data categories) that are used when describing your datasets, systems, policies, etc. Th
I always cringe at the word `simple`, it is subjective and can make people feel unintelligent/unworthy of using the product if they find it difficult.

Maybe something like "we attempt to keep the Fides language as straightforward as possible" or something of that nature? What do you think?

2022-11-15 13:33 UTC, ThomasLaPiana commented on mkdocs/docs/syntax.md
> +The Fides language is intentionally simple. To assure this, Fides declarations use predefined primitives (e.g. data categories) that are used when describing your datasets, systems, policies, etc. Th
```suggestion
The Fides language is intentionally simple. To ensure this, Fides declarations use predefined primitives (e.g. data categories) that are used when describing your datasets, systems, policies, etc. These predefined primitives exist as part of the Fides taxonomy which is maintained in your Fides server so they can be consistently used across your organization's development team. 
```

[I think this is technically correct?](https://newsroom.unl.edu/announce/snr/4471/25500)

2022-11-15 13:34 UTC, ThomasLaPiana commented on mkdocs/docs/taxonomy/data_categories.md
> +| `email`                           | `user.contact`                    |User's email address.                                                                          |
formatting got bumped 🤔

2022-11-15 13:35 UTC, ThomasLaPiana requested changes
Some small comments, overall awesome update!

2023-01-17 02:35 UTC, NevilleS approved these changes
Incorporated @ThomasLaPiana's feedback and merging, thanks

2023-01-17 02:35 UTC, merged